### PR TITLE
UI-Enhancement

### PR DESCRIPTION
**Pull request by Taranpreet10451**
Completed the task.

Sir I will add the description regarding the parameters mentioned on the Predictions page for predicting whether the person is diabetic or not. The details of the parameters will include why they are use for prediction, in place  of the GIF image.

Screenshot 2024-06-13 231238

### CODE REVIEW

**Comment by BamaCharanChhandogi** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Review by BamaCharanChhandogi — CHANGES_REQUESTED** [review]
why did you change the `packege.json file? And make it responsive.

**Comment by Taranpreet10451** [comment]
@BamaCharanChhandogi  Sir please review it I have made the changes.

**Comment by BamaCharanChhandogi** [comment]
please fix merge conflict

**Comment by Taranpreet10451** [comment]
@BamaCharanChhandogi 
Sir, please review it once again.

**Review by BamaCharanChhandogi — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
