### PR TITLE
Added the feature of lazy loading and created a new component for loading spinner that would render whenever loading content is ongoing

### PR DESCRIPTION
**Pull request by imranasumbul**
For enhancement of loading time, the feature of lazy loading is added in App.jsx. Also, a new component for spinner is created that will render whenever the content is loading.

### CODE REVIEW

**Comment by BamaCharanChhandogi** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Review by BamaCharanChhandogi — CHANGES_REQUESTED** [review]
Why did you change the `package.json file`?

**Comment by imranasumbul** [comment]
@BamaCharanChhandogi I have fixed the modifications in package-lock.json file that I had accidentally added. Kindly review it and let me know if any further issues arise.

**Comment by BamaCharanChhandogi** [comment]
your code doesn't work. I am closing this PR.

**Pull request closed without merging**
