### PR TITLE
Fixed hero section

### PR DESCRIPTION
**Pull request by Utsavladia**
#115 
Fixed hero section for both mobile as well as large screeen sizes...

image
image

### CODE REVIEW

**Comment by BamaCharanChhandogi** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Review by BamaCharanChhandogi — CHANGES_REQUESTED** [review]
Why did you change the `package.json file`? 
This design is not responsive. 

image

**Comment by Utsavladia** [comment]
@BamaCharanChhandogi 
I removed the changes of package.lock.json and
Made it responsive although the reposive was needed for navbar not hero section still i fixed it...

image

**Comment by BamaCharanChhandogi** [comment]
The navbar code is perfect when I reload the site extra space showing. please fix it.

image

**Comment by Utsavladia** [comment]
@BamaCharanChhandogi 
I have fixed it... The problem is little bit related to late rendering of the GotoTop button at the bottom right

https://github.com/BamaCharanChhandogi/Diabetes-Prediction/assets/124615886/b6639db9-8d11-4f1f-9f59-a394ee44b020

**Comment by Utsavladia** [comment]
@BamaCharanChhandogi 
fixed

**Comment by BamaCharanChhandogi** [comment]
It still has not fixed that bug. Now, after changes giving new errors in the console.
I am closing this PR. See you in the new issue/PR. Thanks.

image

**Comment by Utsavladia** [comment]
@BamaCharanChhandogi 
should i create a new PR on this issue with the changes based on latest branch to avoid new errors....?

**Pull request closed without merging**
