### PR TITLE
Changing the main page UI

### PR DESCRIPTION
**Pull request by sanskriti-lal**
This PR improves the main page's UI and text content for better user experience. The UI enhancements focuses on visual appeal, responsiveness, and intuitive navigation. Whereas the text adjustments ensure clear and compelling content.

### CODE REVIEW

**Comment by BamaCharanChhandogi** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Comment by sanskriti-lal** [comment]
Hey @BamaCharanChhandogi can you please review my PR

**Review by BamaCharanChhandogi — CHANGES_REQUESTED** [review]
Your code is not responsive! make responsive then I can merge.

**Comment by sanskriti-lal** [comment]
Hey, I've updated the required changes can you please look into it @BamaCharanChhandogi

**Review by BamaCharanChhandogi — APPROVED** [review]
Looks good, thanks.

**Comment by sanskriti-lal** [comment]
Hey @BamaCharanChhandogi you've merged my PR but still it's not reflecting in the leaderboard can you please check and assign the GSSoC labels according.

**Pull request merged**
