### PR TITLE
Added AI Chatbot

### LINKED ISSUE #107: 💡[Feature]: Adding an AI bot
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Integrating a chatbot into a diabetes prediction website, users can receive personalized, interactive, and informative guidance regarding their diabetes risk factors and preventive measures. 

### Use Case

- Chatbots can deliver educational content about diabetes risk factors, symptoms, preventive measures, and lifestyle modifications.
- The chatbot can explain the prediction process,  and provide insights into how specific health factors contribute to the likelihood of developing diabetes.
- Chatbots can offer feedback on lifestyle choices, such as diet and exercise, that impact diabetes risk.

### Benefits

Integrating a chatbot into a diabetes prediction website enhances user experience and engagement.

### Add ScreenShots

Screenshot 2024-05-21 013906
Screenshot 2024-06-17 164703

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by antriksh-9**
## Related Issue
Closes #107.
## Description
Integrating a chatbot into a diabetes prediction website, users can receive personalized, interactive, and informative guidance regarding their diabetes risk factors and preventive measures.
Adding a chatbot into a diabetes prediction website enhances user experience and engagement.

## Video

https://github.com/BamaCharanChhandogi/Diabetes-Prediction/assets/132576984/fa6cf4b2-5701-4bb6-ac38-26f4751a8ab2

### CODE REVIEW

**Comment by BamaCharanChhandogi** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Comment by BamaCharanChhandogi** [comment]
Hi, @antriksh-9,
Thanks for adding this Bot.
When you raised this issue, I thought you wanted to build a chatbot by coding, not using any third party (BotPress).
Although the bot is very nice and perfectly working, the problem is that it is not open source. Later, if someone wants to improve the bot, they will have to do a lot of stuff initially.
Do you understand my concern?

**Review by BamaCharanChhandogi — COMMENTED** [review]
Hi, @antriksh-9,
Thanks for adding this Bot.
When you raised this issue, I thought you wanted to build a chatbot by coding, not using any third party (BotPress).
Although the bot is very nice and perfectly working, the problem is that it is not open source. Later, if someone wants to improve the bot, they will have to do a lot of stuff initially.
Do you understand my concern?

**Comment by antriksh-9** [comment]
> Hi, @antriksh-9, Thanks for adding this Bot. When you raised this issue, I thought you wanted to build a chatbot by coding, not using any third party (BotPress). Although the bot is very nice and perfectly working, the problem is that it is not open source. Later, if someone wants to improve the bot, they will have to do a lot of stuff initially. Do you understand my concern?

Hey @BamaCharanChhandogi, I understand your concern that this is not a open-source bot, but I want to highlight one thing that in future if any one wants to make changes around the chatbot it will be probably in field of improving the conversation flow, making the conversation more engaging & interactive, etc. And this can be easily done using Botpress, we just need the `.bpz` file. The maintainer can easily share the `.bpz.` file and the contributor can work on it and can share back to them. 
Now, since most of the things are perfectly handled by botpress there is a very less probability of an issue being raised around this. So, in my opinion you can go with this.
I have previously worked on this issue on a similar project, you may want to have a look at the conversation here: https://github.com/Nactore-Org/Nacto-Care/pull/113

Also, for a website like Diabetes Prediction Website a chatbot made using Botpress is preferred over a Open AI API based chatbot 
because they are more goal-oriented, making conversation to revolve around the website related stuff only unlike the conversational AI. This is because here the conversation flow are manually generated using botpress studio. Now, it's not that this bot can't answer about the random questions if the user asks so.

**Comment by BamaCharanChhandogi** [comment]
Thanks for the explanation, I understand. Can you write steps for contributing to the Chatbot in the contribution file? Then I can merge.

**Comment by antriksh-9** [comment]
> Thanks for the explanation, I understand. Can you write steps for contributing to the Chatbot in the contribution file? Then I can merge.

Yeah sure, but before that there is one more thing, all the configuration of the bot is present in my botpress account and the link that I have added under the script tag that is also associated with my account. So, I will share the `.bpz file` by exporting the configurations I made on botpress and then you can self host using your email and send the config link back here.
I will then update my link with yours. This will ensure that the ownership of the configurations resides with you.

So, where can I share the `.bpz` file, as this file type is not supported in github markdown.

**Comment by BamaCharanChhandogi** [comment]
You can keep files in the home directory of our project.

**Comment by antriksh-9** [comment]
> You can keep files in the home directory of our project. I will merge, and then I will connect my account later.

I have added the config file.

**Comment by antriksh-9** [comment]
Hey @BamaCharanChhandogi, I have added steps to contribute to chatbot and raised a PR.

**Review by BamaCharanChhandogi — APPROVED** [review]
LGTM, thanks

**Pull request merged**
