### PR TITLE
Updated Favicon #44

### LINKED ISSUE #44: [Bug] Updating Favicon
I will change the vite icon to a better-looking icon.
Kindly assign this to me.

image

### PR DESCRIPTION
**Pull request by its-kumar-yash**
I have updated the favicon.

Fixed #44 

image

### CODE REVIEW

**Comment by BamaCharanChhandogi** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Comment by BamaCharanChhandogi** [comment]
This icon does not look nice. You can try this favicon
https://www.freepik.com/icon/glucometer_2496176#fromView=keyword&page=1&position=81&uuid=3f935bac-d050-42c2-83c1-0cfc161ee22c

**Comment by its-kumar-yash** [comment]
> This icon does not look nice. You can try this favicon https://www.freepik.com/icon/glucometer_2496176#fromView=keyword&page=1&position=81&uuid=3f935bac-d050-42c2-83c1-0cfc161ee22c

Sure..

**Review by BamaCharanChhandogi — APPROVED** [review]
Looks good, thanks.

**Pull request merged**
