### PR TITLE
Added Logo for the website

### PR DESCRIPTION
**Pull request by Soumya6Tiwari**
logo_diabetes
Added a suitable logo for the website  that corresponds to diabetes prediction app.
Screenshot 2024-07-09 020347

### CODE REVIEW

**Comment by BamaCharanChhandogi** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Comment by Soumya6Tiwari** [comment]
@BamaCharanChhandogi  kindly review the PR

**Review by BamaCharanChhandogi — COMMENTED** [review]
It is not looking good. I think without logo will be better.

**Comment by Soumya6Tiwari** [comment]
@BamaCharanChhandogi  ok I respect ur decision but if u want i can replace it with the below logo as it is already present in your website but in the footer section.
Screenshot 2024-07-09 132912
 so please tell

**Comment by BamaCharanChhandogi** [comment]
You can add this logo. And can you change the site name?
❇️ You can add `PreDiaBet` and remove `Diabetes Prediction App`. 

_9b15da1a-55bc-4e75-95a1-8aed7b2f74a6

**Comment by Soumya6Tiwari** [comment]
Screenshot 2024-07-09 233615
@BamaCharanChhandogi 
 Updated the changes as per ur request . Kindly review it once and let me know

**Comment by BamaCharanChhandogi** [comment]
I forgot to mention, can you revert the package.json file? I think you changed it by mistake.

**Pull request closed without merging**
