### PR TITLE
Added CONTRIBUTION.md

### LINKED ISSUE #2: Add Contribution.md
Hey @BamaCharanChhandogi ,
To streamline the contribution process and make it easier for new contributors to get involved, it's important to have clear and detailed contribution guidelines. A CONTRIBUTING.md file outlines the steps and best practices for contributing to the project, ensuring consistency and high-quality contributions.
Please assign me this issue

### PR DESCRIPTION
**Pull request by Santhosh-Siddhardha**
Added Ways to Contribute Section
Added Development Workflow section
Added Issue Report Process Section
Added Help regarding some basics section
Added Pull Request process
Added Community Guidelines
Added Documentation Section
Added Code reviews Section
Added Feature request Section
Added Spread the word Section

Closes #2

### CODE REVIEW

**Comment by BamaCharanChhandogi** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Comment by BamaCharanChhandogi** [comment]
What do you mean by games here?

**Comment by Santhosh-Siddhardha** [comment]
@BamaCharanChhandogi What i want to say is tasks, i tried to say in games language so that everyone can understand it well.

**Review by BamaCharanChhandogi — APPROVED** [review]
Looks good, Thanks.

**Pull request merged**
