### PR TITLE
Added social media icons

### PR DESCRIPTION
**Pull request by Soumya6Tiwari**
Added Suitable social media profile links such as github, quora etc in the footer section
Screenshot 2024-07-09 023127

### CODE REVIEW

**Comment by BamaCharanChhandogi** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Comment by Soumya6Tiwari** [comment]
@BamaCharanChhandogi  kindly review the PR

**Review by BamaCharanChhandogi — CHANGES_REQUESTED** [review]
You do not have to change `package` file.
Please revert it.

**Comment by Soumya6Tiwari** [comment]
@BamaCharanChhandogi  But I only made changes in footer.jsx 
Screenshot 2024-07-09 132448
To add github icon , and quora icon it was necessary to import them from react - icons .

**Comment by BamaCharanChhandogi** [comment]
> @BamaCharanChhandogi But I only made changes in footer.jsx Screenshot 2024-07-09 132448 To add github icon , and quora icon it was necessary to import them from react - icons .


This is all right. I am saying why did you change the `package Json file`. I think It was by mistake. you can undo changes to that file. I mean revert.

**Comment by Soumya6Tiwari** [comment]
@BamaCharanChhandogi  Ok I reverted back the changes

**Review by BamaCharanChhandogi — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
