### PR TITLE
changed footer

### PR DESCRIPTION
**Pull request by jayanththalla**
I have changed the footer part totally by adding a title description and cursor and alignment of the footer
please add the level to this issue and label gssoc
thank you for allowing me to contribute to this repository

### CODE REVIEW

**Comment by BamaCharanChhandogi** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Review by BamaCharanChhandogi — CHANGES_REQUESTED** [review]
why did you change the `package Json` file? And update the Twitter Logo.

**Comment by jayanththalla** [comment]
> why did you change the `package Json` file? And update the Twitter Logo.

sorry i changed the package-lock .json to previous one

**Comment by BamaCharanChhandogi** [comment]
Update the Twitter (X) logo.

**Review by BamaCharanChhandogi — APPROVED** [review]
Looks good, thanks.

**Pull request merged**
