### PR TITLE
Fixed : Static copyright year_Bug  

### PR DESCRIPTION
**Pull request by Meetjain1**
### Description:
This PR enhances the footer section of the website by adding the current copyright year, which is fetched dynamically. This ensures that the copyright year will always be up-to-date without requiring manual updates each year.

#### Benefits:
- **Automation**: The copyright year updates automatically, reducing maintenance overhead.
- **Accuracy**: Ensures the displayed year is always current, improving the website's professionalism.

#### Testing:
- Verified that the current year is displayed correctly in various browsers.
- Checked that the footer styling remains consistent and unaffected by the changes.

### Checklist:
- [X] Tested on multiple browsers
- [X] Verified responsive design
- [X] Ensured no impact on other footer functionalities

@BamaCharanChhandogi have a look on this pr ,I am working under gssoc . Thanks

### CODE REVIEW

**Comment by BamaCharanChhandogi** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Review by BamaCharanChhandogi — APPROVED** [review]
LGTM, Thanks

**Comment by Meetjain1** [comment]
@BamaCharanChhandogi please add label Also , I am working under gssoc . Thanks

**Comment by Meetjain1** [comment]
@BamaCharanChhandogi please add labels of gssoc. Thanks

**Comment by Meetjain1** [comment]
> @BamaCharanChhandogi please add labels of gssoc. Thanks

Hello @BamaCharanChhandogi ?

**Pull request merged**
