### PR TITLE
Fixed Issue No. #140

### PR DESCRIPTION
**Pull request by AnkitLuhar**
there is overlapping of the text in the main page of the webpage ,which shows a unregularity in the styling ,its affect the user-interaction ,Now the issue is solved.
here is the screenShot:
Screenshot (872)

### CODE REVIEW

**Comment by BamaCharanChhandogi** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Comment by AnkitLuhar** [comment]
@BamaCharanChhandogi kindly check and merge the PR.

**Review by BamaCharanChhandogi — CHANGES_REQUESTED** [review]
Your code does not work on another device. Add responsiveness. And you have to look up the navbar also. I will increase the level. Do not worry.

image


image


image

**Comment by AnkitLuhar** [comment]
@BamaCharanChhandogi , kindly check the changes ,if it seems ohk , then i will commit the changes 
here are the ScreenShot:
Screenshot (873)
Screenshot (874)
Screenshot (875)
Screenshot (876)

**Comment by BamaCharanChhandogi** [comment]
It looks good, let's see.

**Comment by AnkitLuhar** [comment]
@BamaCharanChhandogi ,so I commit the changes,do you want to anything to add up or changing in style let me know, and kindly please upgrade the level

**Comment by BamaCharanChhandogi** [comment]
> @BamaCharanChhandogi ,so I commit the changes soon , do you want to anything to add up or changing in style let me know, and kindly please upgrade the level

You can commit, later if required changes I will tell you.

**Comment by AnkitLuhar** [comment]
@BamaCharanChhandogi commit has been done and upgrade the level and merge the PR.

**Review by BamaCharanChhandogi — APPROVED** [review]
LGTM, thanks

**Pull request merged**
