### PR TITLE
Feature Enhancement : Added sorting option in each column

### PR DESCRIPTION
**Pull request by mukilan2815**
image

When user press the column name , it will sort in ascending , if user presses it again then it will sort in descending order.
GSSOC'24

### CODE REVIEW

**Comment by BamaCharanChhandogi** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Review by BamaCharanChhandogi — COMMENTED** [review]
Why did you update the `package JSON` file for the client and server?

**Comment by mukilan2815** [comment]
Just added some packages like mantine and loadsh for better performance.

**Comment by BamaCharanChhandogi** [comment]
By default, the `sorting` icon is not visible. I think we can not understand whether the sorting functionality is available or not.
So I think by default `icon` should be visible.

**Comment by mukilan2815** [comment]
Fixed the changes check it now and close this under GSSOC'24 
#71

**Review by BamaCharanChhandogi — APPROVED** [review]
Looks good, thanks.

**Pull request merged**
