### PR TITLE
added socials and quick links

### LINKED ISSUE #34: [Feat]: Adding social media and quick links
The links are not redirecting properly

q

I wish to fix this

@BamaCharanChhandogi please assign me this issue

### PR DESCRIPTION
**Pull request by Asymtode712**
Fixes #34 

@BamaCharanChhandogi I have added a "/contact" route in quick link as a reference from #33 , so merge this PR first then go for my PR

Also, please add labels and assign me this PR

Thank you!

### CODE REVIEW

**Comment by BamaCharanChhandogi** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Comment by Asymtode712** [comment]
@BamaCharanChhandogi till the time please merge my remaining workflow PRs

**Comment by BamaCharanChhandogi** [comment]
> @BamaCharanChhandogi till the time please merge my remaining workflow PRs

I have already reviewed workflow PRs. You need to update something. Please look at the PR.

**Comment by Asymtode712** [comment]
> > @BamaCharanChhandogi till the time please merge my remaining workflow PRs
> 
> I have already reviewed workflow PRs. You need to update something. Please look at the PR.

@BamaCharanChhandogi I checked each PR but there are no requested changes or updation by you

they are only reamaining with merge

**Comment by BamaCharanChhandogi** [comment]
> > > @BamaCharanChhandogi till the time please merge my remaining workflow PRs
> > 
> > 
> > I have already reviewed workflow PRs. You need to update something. Please look at the PR.
> 
> @BamaCharanChhandogi I checked each PR but there are no requested changes or updation by you
> 
> they are only reamaining with merge


Do you see this type of review?
image

**Comment by Asymtode712** [comment]
@BamaCharanChhandogi No, should I change the PATs?

**Comment by BamaCharanChhandogi** [comment]
> @BamaCharanChhandogi No, should I change the PATs?

yes

**Comment by BamaCharanChhandogi** [comment]
image

do you see this review?

**Comment by Asymtode712** [comment]
@BamaCharanChhandogi  No, I saw it now will make the changes quickly

**Comment by Asymtode712** [comment]
@BamaCharanChhandogi Done with the changes

**Comment by BamaCharanChhandogi** [comment]
I do not know why my reviews are not visible to you. I just wanted to let you know that I requested more changes. 

1. why do you use `a`, I said that you must use the `Link` tag in pages.
2. you can add rest page links according to the navbar.

**Comment by Asymtode712** [comment]
@BamaCharanChhandogi I have replaced all instances of `a` with `Link` and for now `About` in footer navigates to Home page

**Comment by BamaCharanChhandogi** [comment]
> @BamaCharanChhandogi I have replaced all instances of `a` with `Link` and for now `About` in footer navigates to Home page

You can add `FAQ` section instead of `about`

**Comment by Asymtode712** [comment]
@BamaCharanChhandogi Ok as you say

**Comment by Asymtode712** [comment]
@BamaCharanChhandogi Done with the changes please review

**Review by BamaCharanChhandogi — APPROVED** [review]
Looks good, thanks.

**Pull request merged**
