### PR TITLE
Authentication with Google SignUp Functionality 

### LINKED ISSUE #114: 💡[Feature]: Add Authentication
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

1. Authentication ensures that only authorized users have access to sensitive data related to diabetes prediction, such as health information and personal details.
2. It protects against unauthorized access and data breaches, which are critical in the context of health-related applications due to privacy concerns.

### Use Case

Authentication enables the application to manage user accounts securely. Each user can have their data associated with their account, allowing for personalized predictions and recommendations based on their health history and data.

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by codercake**
Fixes #114 

Added a sliding Login and Sign-Up Pages 
LOGIN:
Screenshot 2024-06-26 173956

REGISTER: 
image

### CODE REVIEW

**Comment by BamaCharanChhandogi** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Comment by codercake** [comment]
hello @BamaCharanChhandogi 
i was wondering if i can do the backend of auth too. i ensure to complete it within the schedule. since it is a different logic altogether please dd suitable labels accordingly.

**Comment by BamaCharanChhandogi** [comment]
Thanks for working. But you have to change the design part. The design is not looking good, fix it first of all.
Navabr and footer are not looking good with this `login` page.

**Review by BamaCharanChhandogi — CHANGES_REQUESTED** [review]
I think you did not work with Firebase. So why did you add the Firebase package?

**Comment by codercake** [comment]
could you review the PR? @BamaCharanChhandogi

**Comment by BamaCharanChhandogi** [comment]
Fix merge conflicts then I can merge

**Comment by codercake** [comment]
could you review the updated changes made in the PR? @BamaCharanChhandogi 

> Fix merge conflicts then I can merge

**Comment by BamaCharanChhandogi** [comment]
We don't need this right now.

**Pull request closed without merging**
