### PR TITLE
FIXED Issue #5 : Added a Contact Us Page

### LINKED ISSUE #5: Adding a "Contact Us" Page
The website currently lacks a dedicated "Contact Us" Page. The website should include a dedicated "Contact Us" page. This page should provide the organization's email, contact number, and address, as well as a contact form for users to reach out.

### PR DESCRIPTION
**Pull request by AkshitGarg24**
Fixes #5 

A dedicated "Contact Us" page has been created. First, a "Contact Us" button has been added to the navigation bar. When this button is clicked, it opens a "Contact Us" page that provides details such as email, contact number, business hours, and the address of the organization. Additionally, a contact form has been included to allow users to get in touch directly.

**Request you to please label the PR before merging it. Please label the level of the PR according to the design made.**

Thank You! Happy Coding!

https://github.com/BamaCharanChhandogi/Diabetes-Prediction/assets/153659573/981b610f-260c-433e-a8ae-9087088032d4

### CODE REVIEW

**Comment by BamaCharanChhandogi** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Comment by BamaCharanChhandogi** [comment]
Hi @AkshitGarg24,
can you change the design part, I think the `Contact Us` page is not looking well.

**Comment by AkshitGarg24** [comment]
@BamaCharanChhandogi  Could you please provide more details about how you want this page design to look? Mention a few points, and I'll make the required changes. Alternatively, if you prefer, I can handle the redesign myself.

**Comment by BamaCharanChhandogi** [comment]
> @BamaCharanChhandogi Could you please provide more details about how you want this page design to look? Mention a few points, and I'll make the required changes. Alternatively, if you prefer, I can handle the redesign myself.

sure. can you apply this type of simple design?

image

**Comment by AkshitGarg24** [comment]
> > @BamaCharanChhandogi Could you please provide more details about how you want this page design to look? Mention a few points, and I'll make the required changes. Alternatively, if you prefer, I can handle the redesign myself.
> 
> Sure. can you apply this type of simple design?
> 
> image

Yaa Sure! I will do that and revert back to you.

Thank You!

**Comment by AkshitGarg24** [comment]
@BamaCharanChhandogi The required changes have been made. Please review and let me know if anything else is needed.


https://github.com/BamaCharanChhandogi/Diabetes-Prediction/assets/153659573/343bf292-c291-4d35-81b4-7888a6a47fd3

**Comment by BamaCharanChhandogi** [comment]
> @BamaCharanChhandogi The required changes have been made. Please review and let me know if anything else is needed.
> 
>  ContactUs.mp4

Thanks for the changes. However, our project used `tailwind` CSS. So please write it in tailwind instead of using normal CSS.
Don't worry I will increase the `level`.

**Comment by AkshitGarg24** [comment]
The page has now been implemented using Tailwind CSS. Please review the changes and let me know if any further adjustments are needed.

I did not make any changes to the package.json file. It might get modified automatically when implementing the Contact-Us page.

**Comment by BamaCharanChhandogi** [comment]
> The page has now been implemented using Tailwind CSS. Please review the changes and let me know if any further adjustments are needed.
> 
> I did not make any changes to the package.json file. It might get modified automatically when implementing the Contact-Us page.

Alright. but You have to remove the changes in the `package JSON file`. neither I can't merge.

**Comment by AkshitGarg24** [comment]
The only thing I can do is copy the contents of the package.json file from the main project and then paste it here and then making a commit. Will that be okay, @BamaCharanChhandogi  ?

**Comment by BamaCharanChhandogi** [comment]
> The only thing I can do is copy the contents of the package.json file from the main project and then paste it here and then making a commit. Will that be okay, @BamaCharanChhandogi ?

Yeah, I think you can do it, let's see.

**Comment by AkshitGarg24** [comment]
@BamaCharanChhandogi I have removed changes from package-lock.json file. You can check now.

**Review by BamaCharanChhandogi — APPROVED** [review]
Looks good, Thanks.

**Pull request merged**
