### PR TITLE
UI Enhancement of Navbar

### LINKED ISSUE #67: Navbar not responsive
The content in the navbar is coming out of the navbar, I would like to fix it.
Screenshot (522)
Screenshot (523)

### PR DESCRIPTION
**Pull request by sharmi4590**
## Summary

Solved issue #67 

## Description

Made the navbar responsive for every dimension of screen and also improved the ui of nav menu since the cross button was not responsive.

## Images

https://github.com/user-attachments/assets/841d2a11-0c45-4316-a4a4-b841ba417756

## Issue(s) Addressed

- Template should be strictly **Closes <issue_number>**
- Example: Closes #67 

## Prerequisites

- [x] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTION.md)?

### CODE REVIEW

**Comment by BamaCharanChhandogi** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Comment by sharmi4590** [comment]
Hey @BamaCharanChhandogi Could you please look into my PR

**Comment by sharmi4590** [comment]
Hey, @BamaCharanChhandogi Please merge the PR as from 31st no PRs will be counted

**Review by BamaCharanChhandogi — APPROVED** [review]
Looks good, thanks.

**Pull request merged**
