### PR TITLE
Feat: Added testimonials

### LINKED ISSUE #98: Feat: Adding a testimonials section.
Hello, I would like to add a testimonials section to this website. It consists of user reviews to tell how good the website is.
This makes other users know that it is a good website and people got benefitted from it.

338464852-9affe838-a6a7-4cd4-b94d-f4bbf5ccd239

This is my previous work on testimonials section.
Please assign me this issue, I would like to contribute to this project under GSSoC'24.

### PR DESCRIPTION
**Pull request by nagalakshmi08**
Closes #98 
Hi, I have added the testimonials section which matches with ui and theme of website and are also mobile responsive.

Screenshot 2024-06-13 110111

Mobile view:
Screenshot 2024-06-13 110042

https://github.com/BamaCharanChhandogi/Diabetes-Prediction/assets/121669832/d900aa71-6d08-458c-ade3-83a24d18f708

Please check it and let me know if any changes to be made. Thank you!

### CODE REVIEW

**Comment by BamaCharanChhandogi** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Review by BamaCharanChhandogi — CHANGES_REQUESTED** [review]
Do not modify the 'package.json' file. Update to the latest code, and then I will merge.

**Comment by nagalakshmi08** [comment]
> Do not modify the 'package.json' file. Update to the latest code, and then I will merge.

Please check it now.

**Review by BamaCharanChhandogi — CHANGES_REQUESTED** [review]
You should improve the design of (responsive) arrow buttons.
image

**Comment by nagalakshmi08** [comment]
> You should improve the design of (responsive) arrow buttons. image

I have increased the padding , now it looks good in all types of screens.

**Comment by BamaCharanChhandogi** [comment]
Alright. This issue is showing in the console, please Fix it. Then I will merge.

image

**Comment by BamaCharanChhandogi** [comment]
why some images are not showing?

image

**Comment by nagalakshmi08** [comment]
> why some images are not showing?
> 
> image

Can you please refresh and check it once, all images are being displayed to me.

**Review by BamaCharanChhandogi — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
